import type { Influencer, PublicInfluencer } from '@/lib/types'

export const PUBLIC_INFLUENCER_COLUMNS = [
  'id',
  'slug',
  'display_name',
  'name',
  'platform',
  'avatar_url',
  'city',
  'audience_regions',
  'languages',
  'niches',
  'content_styles',
  'follower_count',
  'engagement_rate',
  'public_bio',
  'price_range_min_inr',
  'price_range_max_inr',
  'sample_content_urls',
  'average_reel_views',
  'audience_age_range',
  'audience_gender_skew',
  'availability',
  'gender',
  'is_available',
  'collaboration_types',
  'preferred_campaign_types',
  'past_collaborations',
  'cover_photo_url',
  'platform_follower_counts',
] as const

export function toPublicInfluencer(
  influencer: Partial<Influencer> & { featured_reel_url?: string | null }
): PublicInfluencer {
  const displayName = influencer.display_name || influencer.name || ''
  return {
    id: String(influencer.id),
    slug: influencer.slug ?? null,
    display_name: displayName,
    name: String(displayName),
    handle: null,
    platform: influencer.platform ?? null,
    profile_url: null,
    avatar_url: influencer.avatar_url ?? null,
    city: influencer.city ?? null,
    audience_regions: influencer.audience_regions ?? [],
    languages: influencer.languages ?? [],
    niches: influencer.niches ?? [],
    content_styles: influencer.content_styles ?? [],
    follower_count: influencer.follower_count ?? null,
    engagement_rate: influencer.engagement_rate ?? null,
    public_bio: influencer.public_bio ?? null,
    price_range_min_inr: influencer.price_range_min_inr ?? null,
    price_range_max_inr: influencer.price_range_max_inr ?? null,
    sample_content_urls: influencer.sample_content_urls ?? [],
    average_reel_views: influencer.average_reel_views ?? null,
    audience_age_range: influencer.audience_age_range ?? null,
    audience_gender_skew: influencer.audience_gender_skew ?? null,
    availability: influencer.availability ?? null,
    gender: influencer.gender ?? null,
    is_available: influencer.is_available ?? true,
    collaboration_types: influencer.collaboration_types ?? [],
    preferred_campaign_types: influencer.preferred_campaign_types ?? [],
    past_collaborations: influencer.past_collaborations ?? [],
    cover_photo_url: influencer.cover_photo_url ?? null,
    platform_follower_counts: influencer.platform_follower_counts ?? {},
    featured_reel_url: influencer.featured_reel_url ?? influencer.sample_content_urls?.[0] ?? null,
  }
}
